// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get welcomeFitBoy => 'Welcome, Fit Boy !';

  @override
  String get filterLabel => 'Filters';

  @override
  String get doinsportApiWarning =>
      'This applications uses doinsport.club\'s API';

  @override
  String get generatedByDallE => 'generated by DALL·E';

  @override
  String get defaultValue => 'default value';

  @override
  String get settingsTitle => 'Settings';

  @override
  String get settingsDarkMode => 'Dark mode';

  @override
  String get settingsColor => 'Color';

  @override
  String get settingsColorPick => 'Pick a color';

  @override
  String get settingsLocale => 'Language';

  @override
  String get settingsVersion => 'Version';

  @override
  String get close => 'Close';

  @override
  String get open => 'Open';
}
